services:
  pg_main2:
    image: postgres:13
    container_name: project2_pg_main2
    restart: unless-stopped
    ports:
      - "5545:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: nest
    volumes:
      - project2_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nest"]
      interval: 10s
      timeout: 5s
      retries: 10

  pg_backup2:
    image: postgres:13
    container_name: project2_pg_backup2
    restart: unless-stopped
    depends_on:
      pg_main2:
        condition: service_healthy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: nest
      BACKUP_KEEP_DAYS: "3"
      BACKUP_INTERVAL_SECONDS: "86400"
    volumes:
      - project2_pgdata:/var/lib/postgresql/data:ro
      - ./uploads:/uploads:ro
      - /mnt/Disk_1TB/Backup/ExamWebsite:/backups
    command: >
      bash -lc '
        while true; do
          TS=$$(date +%Y%m%d_%H%M%S);

          echo "=== BACKUP START: $${TS} ===";

          # Database backup
          PGPASSWORD="$${POSTGRES_PASSWORD}" pg_dump -h pg_main2 -U "$${POSTGRES_USER}" -d "$${POSTGRES_DB}" > /backups/nest_$${TS}.sql;

          # Uploads backup
          tar -czf /backups/uploads_$${TS}.tar.gz -C / uploads;

          # Delete backups older than BACKUP_KEEP_DAYS
          find /backups -type f -mtime +$${BACKUP_KEEP_DAYS} -delete;

          echo "=== BACKUP FINISHED ===";

          sleep "$${BACKUP_INTERVAL_SECONDS}";
        done
      '

volumes:
  project2_pgdata:
