version: '3.8'

services:
  db:
    image: postgres:13
    ports:
      - "5435:5432"   # host:container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - freecodecamp
    volumes:
      - db_data:/var/lib/postgresql/data

  db-backup:
    image: postgres:13
    depends_on:
      - db
    ports:
      - "5436:5432"   # ayrıca host port (istəsən silə bilərsən)
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - freecodecamp
    volumes:
      - /mnt/Disk_256GB/Backup:/backups
      - ./uploads:/uploads
      - db_data:/var/lib/postgresql/data_r
    command: >
      bash -c '
        echo "Backup servisi başladıldı";
        mkdir -p /backups;
        while true; do
          TS=$$(date +%Y%m%d_%H%M%S);
          DUMP_FILE=db_$$TS.sql;
          ARCHIVE_FILE=backup_$$TS.tar.gz;

          echo "Postgres dump hazırlanır...";
          PGPASSWORD=$$POSTGRES_PASSWORD pg_dump \
            -h db \
            -U $$POSTGRES_USER \
            $$POSTGRES_DB > /backups/$$DUMP_FILE;

          echo "DB dump + uploads + raw data arxivlənir...";
          tar -czf /backups/$$ARCHIVE_FILE \
            -C /backups $$DUMP_FILE \
            -C /uploads . \
            -C /var/lib/postgresql data_r;

          rm /backups/$$DUMP_FILE;

          echo "3 gündən köhnə backup-lar silinir...";
          find /backups -type f -name "backup_*.tar.gz" -mtime +3 -delete;

          echo "Növbəti backup 24 saat sonra...";
          sleep 86400;
        done
      '

networks:
  freecodecamp:

volumes:
  db_data:
